/** Mongoose `.select()` projections for list endpoints — omit heavy meta/notes fields. */
export const LIST_FIELD_PROFILES: Record<string, string> = {
  Customer: 'legacyId tenantId name company email phone status totalDue creditLimit ownerId ownerName imageUrl imagePublicId createdAt updatedAt',
  Product: 'legacyId tenantId name sku category productType status price cost stock minStock reorderLevel stockDurationDays stockDurationStartedAt unit imageUrl imagePublicId discontinued createdAt updatedAt',
  Supplier: 'legacyId tenantId name code email phone status due balance imageUrl imagePublicId createdAt updatedAt',
  Employee: 'legacyId tenantId name employeeCode department designation status phone email joinDate imageUrl imagePublicId createdAt updatedAt',
  'Sales order': 'legacyId tenantId customer customerName status total date items attachmentUrl attachmentPublicId attachmentName meta.attachmentUrl meta.attachmentPublicId meta.attachmentName createdAt updatedAt',
  Invoice: 'legacyId tenantId customerId customerName status amount paid due issueDate date dueDate items createdAt updatedAt',
  Lead: 'legacyId tenantId name company phone email source status priority assignedRepId assignedRepName expectedValue nextFollowUpAt nextActionType createdAt updatedAt',
  Deal: 'legacyId tenantId title company status stage value probability assignedRepId assignedRepName expectedCloseDate createdAt updatedAt',
  Quotation: 'legacyId tenantId customer customerName status total date createdAt updatedAt',
  Delivery: 'legacyId tenantId customer customerName status total date orderId items meta.orderId createdAt updatedAt',
  Dispatch: 'legacyId tenantId customer customerName status date createdAt updatedAt',
  Payment: 'legacyId tenantId customerId customer customerName amount method date status invoiceId createdAt updatedAt',
  Return: 'legacyId tenantId customer customerName status total date createdAt updatedAt',
  Complaint: 'legacyId tenantId subject customerName status priority date evidenceImageUrl evidenceImagePublicId createdAt updatedAt',
  'POS transaction': 'legacyId tenantId receiptNo total status date items createdAt updatedAt',
  Category: 'legacyId tenantId name status imageUrl imagePublicId createdAt updatedAt',
  Unit: 'legacyId tenantId name code status createdAt updatedAt',
  Warehouse: 'legacyId tenantId name location status imageUrl imagePublicId createdAt updatedAt',
  'Raw material': 'legacyId tenantId name category sku unit quantity threshold stock reorderLevel cost price stockDurationDays stockDurationStartedAt status imageUrl imagePublicId createdAt updatedAt',
  'Semi-finished product': 'legacyId tenantId name category sku unit stock reorderLevel cost status imageUrl imagePublicId createdAt updatedAt',
  'Finished good': 'legacyId tenantId name category sku unit stock reorderLevel cost price status imageUrl imagePublicId createdAt updatedAt',
  'Stock in': 'legacyId tenantId reference status warehouse date createdAt updatedAt',
  'Stock out': 'legacyId tenantId reference status warehouse date createdAt updatedAt',
  'Stock transfer': 'legacyId tenantId reference status fromWarehouse toWarehouse date createdAt updatedAt',
  'Stock adjustment': 'legacyId tenantId reference status warehouse date createdAt updatedAt',
  'Purchase order': 'legacyId tenantId supplier supplierName status total due balance date expectedDelivery deliveryDate items attachmentUrl attachmentPublicId attachmentName createdAt updatedAt',
  'Production order': 'legacyId tenantId product status plannedQuantity actualQuantity date createdAt updatedAt',
  Project: 'legacyId tenantId name status progress deadline lead priority health budget totalValue totalQty customerName projectId setupStep expectedDeliveryDate items tasks createdAt updatedAt',
  Department: 'legacyId tenantId name status createdAt updatedAt',
  Designation: 'legacyId tenantId name title department status createdAt updatedAt',
  'Leave request': 'legacyId tenantId employeeId employeeName status fromDate toDate createdAt updatedAt',
  Attendance: 'legacyId tenantId employeeId employeeName status date createdAt updatedAt',
  'Payroll run': 'legacyId tenantId period status totalEmployees totalAmount createdAt updatedAt',
  'Salary structure': 'legacyId tenantId name code employeeType status payFrequency effectiveFrom description base totalFixed allowances components assignedEmployeeIds overtimeEnabled otRate holidayOtRate weeklyOffOtRate bonusEnabled bonusPercent workingDays createdAt updatedAt',
  Asset: 'legacyId tenantId name asset category status value purchaseDate imageUrl imagePublicId createdAt updatedAt',
  'Goods received': 'legacyId tenantId supplier product qty status date createdAt updatedAt',
  'Purchase bill': 'legacyId tenantId supplier status total due date createdAt updatedAt',
  'Purchase payment': 'legacyId tenantId supplier status amount date createdAt updatedAt',
  'Purchase return': 'legacyId tenantId supplier status total date createdAt updatedAt',
  Journal: 'legacyId tenantId reference status total date createdAt updatedAt',
  'Ledger entry': 'legacyId tenantId account status debit credit date createdAt updatedAt',
  'Cashbox entry': 'legacyId tenantId type status amount date createdAt updatedAt',
  'Pm project': 'legacyId tenantId name description managerId managerName startDate deadline priority status progress taskCount completedTaskCount createdAt updatedAt',
  'Pm task': 'legacyId tenantId projectId projectName name assignedTo assignedToName assignedToEmail startDate deadline priority status attachmentUrl attachmentName createdAt updatedAt',
};

export function listFieldsFor(resourceName: string): string | undefined {
  return LIST_FIELD_PROFILES[resourceName];
}
